# Generated by Django 5.0.6 on 2024-07-11 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_duel_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='hp',
            field=models.IntegerField(default=100),
        ),
    ]
